baseURL = "https://l-vamsi-krishna.github.io/"
languageCode = "en-us"
title = "Vamsi Krishna's Blog"
theme = "PaperMod"

[author]
    name = "Vamsi Krishna"

[services]
  [services.rss]
    limit = 20

[params]
    author = "Vamsi Krishna"
    ShowFullTextContent = true
    # This enables the "Bio" section on your homepage
    homeInfoParams:
        Title: "Hi, I'm Vamsi Krishna ðŸ‘‹"
        Content: "Sharing insights on Appian, AI."

[[menu.main]]
    name = "Search"
    url = "search/"
    weight = 10