baseURL = "https://l-vamsi-krishna.github.io/"
languageCode = "en-us"
title = "Vamsi Krishna's Blog"
theme = "PaperMod"

# ADD THIS SECTION BELOW
[author]
    name = "Vamsi Krishna"

[params]
    # This helps PaperMod fill in the metadata
    author = "Vamsi Krishna"

[[menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

[services]
  [services.rss]
    limit = 20

[params]
    # This tells PaperMod specifically to include full content in RSS
    ShowFullTextContent = true