baseURL = "https://l-vamsi-krishna.github.io/"
languageCode = "en-us"
title = "My Kali Blog"
theme = "PaperMod"

# ADD THIS SECTION BELOW
[author]
    name = "Vamsi Krishna"

[params]
    # This helps PaperMod fill in the metadata
    author = "Vamsi Krishna"