baseURL = "https://l-vamsi-krishna.github.io/"
languageCode = "en-us"
title = "Vamsi Krishna's Blog"
theme = "PaperMod"

# ADD THIS SECTION BELOW
[author]
    name = "Vamsi Krishna"

[params]
    # This helps PaperMod fill in the metadata
    author = "Vamsi Krishna"
    ShowFullTextContent = true

[[menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

[services]
  [services.rss]
    limit = 20